### ISSUE TITLE
Documenting differences between this and upstream motor record

### ISSUE THREAD

**Issue by hinxx** [EuropeanSpallationSource/motor#1]
Since there are possible differences in behavior and support of this motor record, compared to the upstream, it would be good to have adequate documentation for those differences.

As an user of this motor record, I'm willing to do the initial stab at the changes.

I propose that the original upstream docs/ HTML content is updated with changes and then the pages are published using Github pages (just like for the upstream motor record). Final result would provide a user with a complete picture of what this motor record does and how, including all the upstream documentation.

There needs to be some care taken when doing merge requests or updating this fork with upstream code. One way of doing it is to have a dedicated branch where the modified docs/ are. This branch would never be automatically updated from upstream or pushed as part of pull request to upstream. The the github "Pages" settings can be told to use this specific branch for the location of the HTML files that get published.

**Comment by tboegi** [comment]
@hinxx : I am trying to find a way to make the html being rendered - no luck so far.
The only way I managed is to clone the repo to disk, and open it via a file browser.
Hints are welcome, even how to set up github pages.

However, the documentation here should be up to date, that is the intention, 
especially motorRecord.html

**Comment by hinxx** [comment]
On the github project page, go to Settings -> Pages to configure the GitHub Pages. You need to to select a branch and the folder where the HTML files are; in your motor repo this would be `ess-master` branch and `/docs` folder. After you click save it will take about a minute or two for the page to be ready. Once it is done you will see a link to the web page github created for you..

Here is how it looks when did this after forking your motor repo myself.


![Screenshot_2024-05-21_09-15-32-1](https://github.com/EuropeanSpallationSource/motor/assets/2725009/eca9802c-0f8d-41bf-8e39-b104b4e6d3f4)

**Comment by tboegi** [comment]
Need to update docs/index.html

**Comment by tboegi** [comment]
@ninxx : Thanks for raising this issue.
I think/hope that this can be closed:
https://github.com/EuropeanSpallationSource/motor/commit/60a040268285986c0db21aa76ae29b2c5ffe5e14
